# Generated by Django 5.0.6 on 2024-06-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('section', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('acquisition_date', models.DateField()),
                ('supplier', models.CharField(max_length=200)),
                ('documentation', models.TextField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
