# Generated by Django 5.0.6 on 2024-06-24 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('filed_modified', models.CharField(max_length=50)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('acquisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acquisitions.acquisition')),
            ],
        ),
    ]
