# Generated by Django 5.0.6 on 2024-06-24 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0002_acquisitionhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acquisitionhistory',
            old_name='filed_modified',
            new_name='field_modified',
        ),
    ]
