# Generated by Django 5.0.6 on 2024-06-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisitions', '0003_rename_filed_modified_acquisitionhistory_field_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisition',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='acquisition_date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
